---

- src: https://github.com/grzegorznowak/ansible-role-nix.git
  name: nix
  scm: git
  version: patch-1

- name: geerlingguy.pip
  version: 2.1.0

- src: https://github.com/grzegorznowak/cardano-node-role.git
  name: grzegorznowak.cardano_node
  scm: git
  version: main

  
