---

### CORE PROVISIONING ###
- name: Converge common for all
  hosts: all
  vars:
    nix_user: nix
    pab_sources: "/home/{{ nix_user }}/pab"
    nix_source_file: "/home/nix/.nix-profile/etc/profile.d/nix.sh"

    # which tag to git checkout to when converging the PAB
    default_pab_commit: 7f53f18dfc788bf6aa929f47d840efa1247e11fd

    cardano_user: nix
    active_network: dev
    cardano_group: cardano
    cardano_install_method: dist
    cardano_node_socket_path: "/home/{{ cardano_user }}/cardano_devnet/private-testnet/node-bft1/node.sock"
    ansible_bender:
      base_image: "nixos/nix:2.6.0"
      
      working_container:
        volumes:
          - "{{ playbook_dir }}:/src"
      
      target_image:
        name: pab

  pre_tasks:

    - name: "Add the {{ nix_user }} user"
      ansible.builtin.user:
        name: "{{ nix_user }}"
        comment: "{{ nix_user }}"
        shell: /bin/bash
        home: "/home/{{ nix_user }}"

  post_tasks:

    - name: "Add user {{ nix_user }} to sudo"
      lineinfile:
        path: "/etc/sudoers.d/{{ nix_user }}"
        line: '{{ nix_user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'

    - name: Set includedir in sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"

    - name: Update bashrc for the nix user
      lineinfile:
        dest: "/home/{{ nix_user }}/.bashrc"
        line: "source {{ nix_source_file }}"
        regexp: "^source /home/nix/"
        owner: "{{ nix_user }}"
        state: present
        insertafter: EOF
        create: true

    - name: Change the ownership of the /nix folder for the nix user
      file:
        path: /nix
        owner: "{{ nix_user }}"
        mode: '0744'

    - name: Add IOHK binary caches
      blockinfile:
        path: /etc/nix/nix.conf
        create: true
        block: |-
          experimental-features = nix-command
          substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Chackout the PAB repo
      git:
        repo: https://github.com/input-output-hk/plutus-apps
        dest: "{{ pab_sources }}"
        version: "{{ lookup('env', 'PAB_COMMIT') | default(default_pab_commit, true) }}"
        force: true
      become: true
      become_user: "{{ nix_user }}"

    - name: Make plutus playground not be using SSL
      replace:
        path: "{{ pab_sources }}/plutus-playground-client/webpack.config.js"
        regexp: "https: true"
        replace: "https: false"

    - name: Make plutus playground listen on the public interface
      lineinfile:
        path: "{{ pab_sources }}/plutus-playground-client/webpack.config.js"
        regexp: 'host: "0\.0\.0\.0",'
        insertafter: 'port: 8009,'
        line: 'host: "0.0.0.0",'

    - name: Build the PAB library
      shell: >-
        source {{ nix_source_file }}
        && nix build -f default.nix plutus-apps.haskell.packages.plutus-pab.components.library
      become: true
      become_user: "{{ nix_user }}"
      args:
        executable: /bin/bash
        chdir: "{{ pab_sources }}"

    - name: Build the Playground
      shell: >-
        source {{ nix_source_file }}
        && nix-build -A plutus-playground.server
      become: true
      become_user: "{{ nix_user }}"
      args:
        executable: /bin/bash
        chdir: "{{ pab_sources }}"

    - name: Bootstrap the nix-shell
      shell: >-
        source {{ nix_source_file }}
        && nix-shell
      become: true
      become_user: "{{ nix_user }}"
      args:
        executable: /bin/bash
        chdir: "{{ pab_sources }}"

    - name: Sync helper scripts to bin
      copy:
        src: ../../scripts/
        dest: "/home/{{ nix_user }}/bin/"
        owner: "{{ nix_user }}"
        group: "{{ nix_user }}"
        mode: "a+x"

    - name: Update bashrc to export cardano socket
      lineinfile:
        dest: "/home/{{ cardano_user }}/.bashrc"
        line: "export CARDANO_NODE_SOCKET_PATH={{ cardano_node_socket_path }}"
        regexp: "^export CARDANO_NODE_SOCKET_PATH="
        owner: "{{ cardano_user }}"
        state: present
        insertafter: EOF
        create: true

    - name: Ops | Create wallets we want
      cardano_wallet:
        cardano_bin_path: "{{ cardano_bin_path }}"
        wallets_path: "/home/{{ cardano_user }}/addresses"
        name:
          - pab1
          - pab2
          - pab3
        active_network: "dev"
        testnet_magic: "42"  # only used on testnet
      become: true
      become_user: "{{ cardano_user }}"
      register: wallet_results
  roles:
    - grzegorznowak.cardano_node
